//file:noinspection GroovyAssignabilityCheck
plugins {
    id 'fabric-loom' version "${fabric_loom}"//全局属性
    id 'maven-publish'
    id 'idea'
}
version = project.mod_version
group = project.maven_group
base {
    archivesName = project.archives_base_name
}
dependencies {
    //## mod依赖
    minecraft("com.mojang:minecraft:${minecraft}")
    modApi("net.fabricmc:fabric-loader:${fabric_loader}")//全局属性
    modApi("net.fabricmc.fabric-api:fabric-api:${fabric_api}")
    modApi("com.terraformersmc:modmenu:${modmenu}")
    //## 非mod依赖
    mappings("net.fabricmc:yarn:${yarn_mappings}:v2")
    compileOnlyApi(annotationProcessor("org.projectlombok:lombok:${lombok}"))
    //## 非依赖
}
processResources {
    inputs.property('version', project.version)
    filesMatching('fabric.mod.json') {
        expand('version': project.version)
    }
}
java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
publishing {
    publications {
        create('mavenJava', MavenPublication) {
            artifactId = "${archives_base_name}-${minecraft}"
            from(components['java'] as SoftwareComponent)
        }
    }
}
jar {
    archiveFileName = "${builtJarName()}-dev.jar"
}
sourcesJar {
    archiveFileName = "${builtJarName()}-dev-sources.jar"
}
remapJar {
    archiveFileName = "${builtJarName()}.jar"
}
remapSourcesJar {
    archiveFileName = "${builtJarName()}-sources.jar"
}
fabricApi {
    configureDataGeneration()
}
tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}
loom {
    mods {
        register("${mod_id}") { s ->
            s.sourceSet('main')
        }
    }
    accessWidenerPath = file("src/main/resources/${mod_id}.accessWidener")
    runs {
        datagen {
            inherit(client)
            property('fabric-api.datagen.modid', "${project.properties['mod_id']}")
        }
        client {
            property('fabric-tag-conventions-v2.missingTagTranslationWarning', 'VERBOSE')
            property('fabric.systemLibraries', "${project.properties['hotswap_fatjar']}")
            vmArgs(
              '-XX:+AllowEnhancedClassRedefinition',
              '-XX:HotswapAgent=fatjar',
              '-Xlog:redefine+class*=info'
            )
            programArgs('--username=Phoupraw')
        }
    }
}
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

String builtJarName() {
    return "${archives_base_name}-${minecraft}-${version}"
}

mkdir('build/datagen')