# 全局属性 file:///%USERPROFILE%/.gradle/gradle.properties
## 基础依赖 https://fabricmc.net/develop
minecraft = 1.21.1
yarn_mappings = 1.21.1+build.3
fabric_api = 0.115.3+1.21.1
## 本mod信息
mod_id = minimalism_leaf_decay
mod_version = 0.2.1
maven_group = phoupraw.mcmod
archives_base_name = MinimalismLeafDecay
## mod依赖
### Mod Menu - https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu = 11.0.3
### YetAnotherConfigLib - https://modrinth.com/mod/yacl/versions?l=fabric - https://maven.isxander.dev/#/releases/dev/isxander/yacl/yet-another-config-lib-fabric
yacl = 3.6.5+1.20.1-fabric
### EMI - https://modrinth.com/mod/emi/versions?platform=fabric
emi = _
### REI - https://modrinth.com/mod/rei/versions?l=fabric
rei = _
### Jade - https://www.curseforge.com/minecraft/mc-mods/jade/files/all?page=1&pageSize=20&version=1.21&gameVersionTypeId=4
jade = 5493289
### Trinkets - https://modrinth.com/mod/trinkets/versions?l=fabric
trinkets = _
### Client Arguments - https://maven.xpple.dev/maven2/dev/xpple/clientarguments/
clientarguments = 1.9
# Farmer's Delight - https://modrinth.com/mod/farmers-delight-refabricated/versions?g=1.21.1
farmersdelight = 1.21.1-3.1.2
## 非mod依赖
### 非依赖