## 基础依赖 https://fabricmc.net/develop
minecraft = 1.21.1
yarn_mappings = 1.21.1+build.3
loader = 0.16.9
fabric_api = 0.109.0+1.21.1
## 本mod信息
mod_id = minimalism_leaf_decay
mod_version = 0.2.0
maven_group = phoupraw.mcmod
archives_base_name = MinimalismLeafDecay
## mod依赖
### Mod Menu - https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu = 11.0.3
## 非mod依赖
### Lombok
lombok = 1.18.30
### 非依赖

